Fix link to License
dracula/dracula-ui pull request #131
Opened 2022-09-29 22:23 UTC by koki-develop

Thank you for the wonderful library! ❤️ 
The link to license was incorrect, so fixed it 👍

2022-09-29 22:44 UTC, itaibo commented on website/pages/welcome.js
> +            <li><Anchor href="https://github.com/dracula/dracula-ui/blob/master/LICENSE">License</Anchor></li>
```suggestion
            <li><Anchor href="https://github.com/dracula/dracula-ui/blob/main/LICENSE">License</Anchor></li>
```

2022-09-29 22:44 UTC, itaibo requested changes

2022-09-29 22:44 UTC, itaibo commented on website/pages/welcome.js
> +            <li><Anchor href="https://github.com/dracula/dracula-ui/blob/master/LICENSE">License</Anchor></li>
Branch was renamed to `main`
```suggestion
            <li><Anchor href="https://github.com/dracula/dracula-ui/blob/main/LICENSE">License</Anchor></li>
```

2022-09-29 22:50 UTC, itaibo approved these changes

2022-10-03 13:34 UTC, luxonauta commented
Thank you very much, Koki! 😊

These little details **make all the difference**! Looking forward to your following contributions! ✨

2022-10-03 13:34 UTC, merged